[tools]
go = "latest"
node = "latest"
opam = "latest"
python = "latest"
uv = "latest"
lazygit = "latest"
"ubi:tldr-pages/tlrc" = { version = "latest", exe = "tldr" }
neovim = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
